# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ArnaudSnomsed | Blog
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  J'ai une vie somme toute assez normale
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arnaudsnomsed.github.io" # the base hostname & protocol for your site
# twitter_username: arnaudsnomsed
# github_username:  arnaudsnomsed

# Build settings
markdown: kramdown
lang: fr
comments: true
paginate: 12
excerpt_separator: "<!-- more -->"
exclude:
  - Gemfile

remote_theme: yous/whiteglass
#remote_theme: pages-themes/hacker@v0.2.0

#theme: jekyll-whiteglass

safe: true

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-archives

whitelist:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-archives

sass:
    sass_dir: _sass

google_analytics: G-J2R4VJ04JL
future: false

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/