name: Build every hour

on:
  schedule:
    - cron: "22 * * * *" # Run at the end of every day.
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@master
        with:
          args:
            "-X POST -H 'Authorization: token $'
            -H 'Accept: application/vnd.github.ant-man-preview+json'
            https://api.github.com/repos/ArnaudSnomsed/arnaudsnomsed.github.io/pages/builds"
